- hosts: wordpress
  become: yes
  vars:
    wp_db_name: wordpress
    wp_user: wordpress
    wp_user_pass: wordpress
    wp_root_pass: 123wordpress
    web_root: /var/www/wordpress

  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Install Apache, MySQL, and PHP
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
        state: present

    - name: Install Python MySQL dependencies
      apt:
        name: python3-pymysql
        state: present

    - name: Create MySQL WordPress user
      mysql_user:
        name: "{{ wp_user }}"
        password: "{{ wp_user_pass }}"
        priv: "{{ wp_db_name }}.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create WordPress database
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present
        login_user: "{{ wp_user }}"
        login_password: "{{ wp_user_pass }}"

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes

    - name: Copy wp-config-sample.php to wp-config.php
      command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
      args:
        creates: /var/www/wordpress/wp-config.php

    - name: Set permissions for WordPress directory
      file:
        path: "{{ web_root }}"
        owner: www-data
        group: www-data
        mode: '0755'
        state: directory

    - name: Configure wp-config.php
      lineinfile:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "DB_NAME", line: "define('DB_NAME', '{{ wp_db_name }}');" }
        - { regexp: "DB_USER", line: "define('DB_USER', '{{ wp_user }}');" }
        - { regexp: "DB_PASSWORD", line: "define('DB_PASSWORD', '{{ wp_user_pass }}');" }
        - { regexp: "DB_HOST", line: "define('DB_HOST', 'localhost');" }

    - name: Update Apache VirtualHost for WordPress
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'DocumentRoot /var/www/html'
        replace: 'DocumentRoot {{ web_root }}'
      notify: Restart Apache

    - name: Enable Apache mod_rewrite
      command: a2enmod rewrite
      notify: Restart Apache

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted